#!/usr/bin/sh

cd /mgi/se/readonlysrc

echo "removing old indexes..."
rm .glimpse*

echo "generating new indexes..."
timex glimpseindex -H /mgi/se/readonlysrc/ -B -M 32 -n -b /mgi/se/readonlysrc/

echo "changing permissions on indexes..."
chmod a+r /mgi/se/readonlysrc/.glimpse*
chmod g+w /mgi/se/readonlysrc/.glimpse*

echo "done"
