#!/usr/local/bin/python

import sys
sys.path.append ('/usr/local/mgi/live/lib/python/')

import httpReader
import time
import string

url = 'http://www.informatics.jax.org/searches/expression_report.cgi?_Refs_key=92242&returnType=assays&order=symbol'

start = time.time()
(s, err) = httpReader.getURL (url, timeout = 300)
stop = time.time()

if not err:
	print 'retrieved gray data page'
	print 'length: ', len(string.join(s,''))
else:
	print 'failed to retrieve gray data page'
	print 'error: ', err

print 'time: ', (stop - start), ' sec'
