#!/usr/local/bin/python

import sys
import regsub

for filename in sys.argv[1:]:
	fp = open (filename, 'r')
	lines = fp.readlines()
	fp.close ()

	count = 0
	for line in lines:
		line = regsub.gsub ('\t', '        ', line)
		if len (line) > 78:
			count = count + 1
	if count > 0:
		print '%s (%d)' % (filename, count)

