#!/bin/sh

# monitor memory usage and CPU for a single process, specified by PID

USAGE="Usage: $0 <pid>\n
    Watch the memory and CPU usage (using prstat) for the given process,\n
    re-sampling every five seconds and showing the history over time.\n
    (useful for watching the memory footprint of a given script)\n
"

if [ "$1" = "" ]; then
echo $USAGE
exit 1
fi

PID="$1"

WHICHPRSTAT=`which prstat 2>&1 > /dev/null`
if [ "$?" = "0" ]; then
	prstat -p ${PID} 1 1 | grep PID
	CMD="prstat -p ${PID} 1 1"
else
	top -n 1 -b -p ${PID} | grep PID
	CMD="top -n 1 -b -p ${PID}"
fi

PID=$1
PROCCOUNT=`${CMD} | grep ${PID} | wc -l`

while [ "${PROCCOUNT}" = "1" ]; do
${CMD} | grep ${PID}
sleep 5
PROCCOUNT=`${CMD} | grep ${PID} | wc -l`
done
ENDTIME=`uptime | awk "{print $1}"`
echo "Process ${PID} finished at ${ENDTIME}"
